### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by sari777** [unclevito2017/Quantum-mining-puzzle-66#1]
whats the function of this program.?

**Comment by unclevito2017** [comment]
To connect to the IBM Quantum computer and use it to find the answer to puzzle 66

**Comment by sari777** [comment]
how to use sir.?

**Comment by unclevito2017** [comment]
Well it is in progress and has issues to overcome (hopefully). But you will need to go to https://quantum.ibm.com/ and get an account so you can be assigned your personal API so you can hook up to the Quantum computer for use if and when the program is ready. Once the program is functional I will add further instructions

**Comment by sari777** [comment]
ok sir thanks

**Comment by sari777** [comment]
> Well it is in progress and has issues to overcome (hopefully). But you will need to go to https://quantum.ibm.com/ and get an account so you can be assigned your personal API so you can hook up to the Quantum computer for use if and when the program is ready. Once the program is functional I will add further instructions
