### ISSUE TITLE
Error massage

### ISSUE THREAD

**Issue by ashraful1978** [unclevito2017/Quantum-mining-puzzle-66#4]
Dear Concern,
The program look like good; but found in error. Attached screenshot for your kind reference. Please help to us an running the program,

![image](https://github.com/unclevito2017/Quantum-mining-puzzle-66/assets/119058177/c1c3060d-f9ba-48f2-adf9-f306eb53b863)

**Comment by unclevito2017** [comment]
It appears that you are already connected to the API when you try to have 2 connections to the api  you get that error. The API stays connected for approximately 1 month before having to login again so run pthon3 quantum-check-if-connected.py   this will tell you if you are already connected if you are you will get  an output like this  python3 quantum-check-if-connected.py
C:\kangaroo\quantum-check-if-connected.py:4: DeprecationWarning: The package qiskit.providers.ibmq is being deprecated. Please see https://ibm.biz/provider_migration_guide to get instructions on how to migrate to qiskit-ibm-provider (https://github.com/Qiskit/qiskit-ibm-provider) and qiskit-ibm-runtime (https://github.com/Qiskit/qiskit-ibm-runtime).
  IBMQ.load_account()
C:\kangaroo\quantum-check-if-connected.py:4: DeprecationWarning: The qiskit.IBMQ entrypoint and the qiskit-ibmq-provider package (accessible from 'qiskit.providers.ibmq`) are deprecated and will be removed in a future release. Instead you should use the qiskit-ibm-provider package which is accessible from 'qiskit_ibm_provider'. You can install it with 'pip install qiskit_ibm_provider'. Just replace 'qiskit.IBMQ' with 'qiskit_ibm_provider.IBMProvider'
  IBMQ.load_account()
Connected to IBM Quantum: <AccountProvider for IBMQ(hub='ibm-q', group='open', project='main')>
